---
- name: Install PHP
  apt: name=php state=present

- name: Install PHP mod for Apache2
  apt: name=libapache2-mod-php7.0 state=present

- name: Install PHP extension zip
  apt: name=php-zip state=present

- name: Install PHP extension xml
  apt: name=php-xml state=present

- name: Install PHP extension mbstring
  apt: name=php-mbstring state=present
